### ISSUE TITLE
After master switches, one replica lost pg_control file

### ISSUE THREAD

**Issue by michael-sayapin** [timescale/timescaledb-kubernetes#301]
**Describe the bug**
We have a three-node cluster, db0, db1, db2. When db2 was the master, due to a billing issue the node was shut down. The master successfully switched to db0. When we brought the node up, I restarted the StatefulSet. However, db1 failed to come up:

```
Traceback (most recent call last):
--
2021-07-18 17:28:55 | File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 718, in controldata
2021-07-18 17:28:55 | data = subprocess.check_output([self.pgcommand('pg_controldata'), self._data_dir], env=env)
2021-07-18 17:28:55 | File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
2021-07-18 17:28:55 | **kwargs).stdout
2021-07-18 17:28:55 | File "/usr/lib/python3.7/subprocess.py", line 487, in run
2021-07-18 17:28:55 | output=stdout, stderr=stderr)
2021-07-18 17:28:55 | subprocess.CalledProcessError: Command '['pg_controldata', '/var/lib/postgresql/data']' returned non-zero exit status 1.
2021-07-18 17:29:05 | pg_controldata: fatal: could not read file "/var/lib/postgresql/data/global/pg_control": read 0 of 296
```

I checked and it seems that /var/lib/postgresql/data/global/pg_control file is empty, 0 bytes.

**To Reproduce**
Bootstrap three nodes, shut down the master's node, bring the node back.

**Expected behavior**
The replica comes up successfully.

**Deployment**

- What is in your `values.yaml`

```
replicaCount: 3
nameOverride: timescaledb
clusterName:
version: 13
image:
  repository: timescale/timescaledb-ha
  tag: pg13.3-ts2.3.0-p0
  pullPolicy: IfNotPresent

secretNames:
  credentials:  
  certificate:  
  pgbackrest:  

backup:
  enabled: true
  pgBackRest:
    compress-type: lz4
    process-max: 4
    start-fast: "y"
    repo1-retention-diff: 10
    repo1-retention-full: 10
    repo1-type: s3
    repo1-cipher-type: "none"
    repo1-s3-uri-style: path
  pgBackRest:archive-push: {}
  pgBackRest:archive-get: {}
  jobs:
    - name: full-weekly
      type: full
      schedule: "12 04 * * 0"
    - name: incremental-daily
      type: incr
      schedule: "12 02 * * *"
  envFrom:
  - secretRef:
      name: extra-pgbackrest-secrets
  env:

bootstrapFromBackup:
  enabled: false
  repo1-path:
  secretName: pgbackrest-bootstrap

env:
envFrom:

patroni:
  log:
    level: WARNING
  bootstrap:
    method: restore_or_initdb
    restore_or_initdb:
      command: >
        /etc/timescaledb/scripts/restore_or_initdb.sh
        --encoding=UTF8
        --locale=C.UTF-8
      keep_existing_recovery_conf: true
    post_init: /etc/timescaledb/scripts/post_init.sh
    dcs:
      loop_wait: 10
      maximum_lag_on_failover: 33554432
      postgresql:
        parameters:
          archive_command: "/etc/timescaledb/scripts/pgbackrest_archive.sh %p"
          archive_mode: 'on'
          archive_timeout: 1800s
          autovacuum_analyze_scale_factor: 0.02
          autovacuum_naptime: 5s
          autovacuum_max_workers: 10
          autovacuum_vacuum_cost_limit: 500
          autovacuum_vacuum_scale_factor: 0.05
          log_autovacuum_min_duration: 1min
          hot_standby: 'on'
          log_checkpoints: 'on'
          log_connections: 'on'
          log_disconnections: 'on'
          log_line_prefix: "%t [%p]: [%c-%l] %u@%d,app=%a [%e] "
          log_lock_waits: 'on'
          log_min_duration_statement: '1s'
          log_statement: ddl
          max_connections: 1000
          max_prepared_transactions: 150
          shared_preload_libraries: timescaledb,pg_stat_statements,pg_repack
          ssl: 'on'
          ssl_cert_file: '/etc/certificate/tls.crt'
          ssl_key_file: '/etc/certificate/tls.key'
          tcp_keepalives_idle: 900
          tcp_keepalives_interval: 100
          temp_file_limit: 1GB
          timescaledb.passfile: '../.pgpass'
          unix_socket_directories: "/var/run/postgresql"
          unix_socket_permissions: '0750'
          wal_level: hot_standby
          wal_log_hints: 'on'
          # ADDED BY US
          checkpoint_completion_target: 0.9
          effective_cache_size: 12GB
          full_page_writes: 'on'
          maintenance_work_mem: 2GB
          max_locks_per_transaction: 512
          max_parallel_workers: 40
          max_parallel_workers_per_gather: 20
          random_page_cost: 3
          shared_buffers: 3GB
          synchronous_commit: off
          temp_buffers: 128MB
          work_mem: 64MB
          timezone: 'UTC'
          datestyle: 'iso, mdy'
        use_pg_rewind: true
        use_slots: true
      retry_timeout: 10
      ttl: 30
  kubernetes:
    role_label: role
    scope_label: cluster-name
    use_endpoints: true
  postgresql:
    create_replica_methods:
    - basebackup
    - pgbackrest
    pgbackrest:
      command: /etc/timescaledb/scripts/pgbackrest_restore.sh
      keep_data: true
      no_params: true
      no_master: true
    basebackup:
    - waldir: "/var/lib/postgresql/wal/pg_wal"
    recovery_conf:
      restore_command: /etc/timescaledb/scripts/pgbackrest_archive_get.sh %f "%p"
    callbacks:
      on_role_change: /etc/timescaledb/scripts/patroni_callback.sh
      on_start: /etc/timescaledb/scripts/patroni_callback.sh
      on_reload: /etc/timescaledb/scripts/patroni_callback.sh
      on_restart: /etc/timescaledb/scripts/patroni_callback.sh
      on_stop: /etc/timescaledb/scripts/patroni_callback.sh
    authentication:
      replication:
        username: standby
      superuser:
        username: postgres
    listen: 0.0.0.0:5432
    pg_hba:
    - local     all             postgres                              peer
    - local     all             all                                   md5
    - hostnossl all,replication all                all                reject
    - hostssl   all             all                127.0.0.1/32       md5
    - hostssl   all             all                ::1/128            md5
    - hostssl   replication     standby            all                md5
    - hostssl   all             all                all                md5
    use_unix_socket: true
  restapi:
    listen: 0.0.0.0:8008

callbacks:
  configMap:  

postInit:
  - configMap:
      name: custom-init-scripts
      optional: true
  - secret:
      name: custom-secret-scripts
      optional: true

loadBalancer:
  enabled: false
  port: 5432
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
  spec:

replicaLoadBalancer:
  enabled: false
  port: 5432
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
  spec:

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

persistentVolumes:
  data:
    enabled: true
    size: 500Gi
    storageClass: "longhorn"
    subPath: ""
    mountPath: "/var/lib/postgresql"
    annotations: {}
    accessModes:
      - ReadWriteOnce
  wal:
    enabled: true
    size: 50Gi
    subPath: ""
    storageClass: "longhorn"
    mountPath: "/var/lib/postgresql/wal"
    annotations: {}
    accessModes:
      - ReadWriteOnce

fullWalPrevention:
  enabled: false
  checkFrequency: 30
  thresholds:
    readOnlyFreePercent: 5
    readOnlyFreeMB: 64
    readWriteFreePercent: 8
    readWriteFreeMB: 128

resources: {}

sharedMemory:
  useMount: false

timescaledbTune:
  enabled: false
  args: {}

pgBouncer:
  enabled: true
  port: 6432
  config:
    server_reset_query: DISCARD ALL
    max_client_conn: 500
    default_pool_size: 12
    pool_mode: transaction
    ignore_startup_parameters: extra_float_digits
  pg_hba:
  - local     all postgres                   peer
  - host      all postgres,standby 0.0.0.0/0 reject
  - host      all postgres,standby ::0/0     reject
  - hostssl   all all              0.0.0.0/0 md5
  - hostssl   all all              ::0/0     md5
  - hostnossl all all              0.0.0.0/0 reject
  - hostnossl all all              ::0/0     reject
  userListSecretName:

networkPolicy:
  enabled: false
  prometheusApp: prometheus
  ingress:

nodeSelector: {}

prometheus:
  enabled: true
  image:
    repository: wrouesnel/postgres_exporter
    tag: v0.7.0
    pullPolicy: Always
  env:
  volumes:
  volumeMounts:

podManagementPolicy: Parallel
podAnnotations: {}
tolerations: []
affinityTemplate: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchLabels:
            app: {{ template "timescaledb.fullname" . }}
            release: {{ .Release.Name | quote }}
            cluster-name: {{ template "clusterName" . }}
    - weight: 50
      podAffinityTerm:
        topologyKey: failure-domain.beta.kubernetes.io/zone
        labelSelector:
          matchLabels:
            app: {{ template "timescaledb.fullname" . }}
            release: {{ .Release.Name | quote }}
            cluster-name: {{ template "clusterName" . }}
affinity: {}

rbac:
  create: true

serviceAccount:
  create: true
  name:

unsafe: false

debug:
  execStartPre:  
```

- What version of the Chart are you using?

0.8.2.

- What is your Kubernetes Environment (for exampe: GKE, EKS, minikube, microk8s)

Bare metal k3s, 3 nodes.

**Deployment**

```
kubectl get all,secret,configmap,endpoints,pvc -L role -l release=$RELEASE
```

```
NAME                   READY   STATUS    RESTARTS   AGE    ROLE
pod/db-timescaledb-0   4/4     Running   0          29h    master
pod/db-timescaledb-1   3/4     Running   0          108m
pod/db-timescaledb-2   4/4     Running   0          29h    replica

NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE   ROLE
service/db                      ClusterIP   10.43.121.159   <none>        6432/TCP,5432/TCP   26d   master
service/db-config               ClusterIP   None            <none>        8008/TCP            26d
service/db-prometheus           ClusterIP   10.43.16.206    <none>        9187/TCP            26d
service/db-replica              ClusterIP   10.43.198.184   <none>        6432/TCP,5432/TCP   26d   replica
service/db-timescaledb-backup   ClusterIP   10.43.217.28    <none>        8081/TCP            26d

NAME                              READY   AGE   ROLE
statefulset.apps/db-timescaledb   2/3     26d

NAME                                             SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE   ROLE
cronjob.batch/db-timescaledb-full-weekly         12 04 * * 0   False     0        13h             26d
cronjob.batch/db-timescaledb-incremental-daily   12 02 * * *   False     0        15h             26d

NAME                                  DATA   AGE   ROLE
configmap/db-timescaledb-patroni      1      26d
configmap/db-timescaledb-pgbackrest   1      26d
configmap/db-timescaledb-pgbouncer    2      26d
configmap/db-timescaledb-scripts      8      26d

NAME                              ENDPOINTS                           AGE   ROLE
endpoints/db                      10.42.2.163:5432,10.42.2.163:6432   26d
endpoints/db-config               10.42.0.122:8008,10.42.2.163:8008   26d
endpoints/db-prometheus           10.42.0.122:9187,10.42.2.163:9187   26d
endpoints/db-replica              10.42.0.122:6432,10.42.0.122:5432   26d   replica
endpoints/db-timescaledb-backup   10.42.2.163:8081                    26d

NAME                                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   ROLE
persistentvolumeclaim/storage-volume-db-timescaledb-0   Bound    pvc-c11ccf81-27d4-4c80-9332-b2d815139c83   500Gi      RWO            longhorn       26d
persistentvolumeclaim/storage-volume-db-timescaledb-1   Bound    pvc-cc74d3f5-b5ed-4f62-bcff-b236df488a6e   500Gi      RWO            longhorn       26d
persistentvolumeclaim/storage-volume-db-timescaledb-2   Bound    pvc-969b46cf-441a-47f5-97f8-3490f74ded5d   500Gi      RWO            longhorn       26d
persistentvolumeclaim/wal-volume-db-timescaledb-0       Bound    pvc-285d728c-baac-4d9e-9f6c-34d33c4eb9da   50Gi       RWO            longhorn       26d
persistentvolumeclaim/wal-volume-db-timescaledb-1       Bound    pvc-1757ce41-efdc-4dad-b544-c59ac2f36ee5   50Gi       RWO            longhorn       26d
persistentvolumeclaim/wal-volume-db-timescaledb-2       Bound    pvc-35c0f3e7-3fcb-4d8e-a088-e8a50a82e023   50Gi       RWO            longhorn       26d
```

**Comment by michael-sayapin** [comment]
Resolved it by deleting the PVC and letting the Pod bootstrap from pg_basebackup. Took a while, but now everything running well again.
