### ISSUE TITLE
ERROR: create_config_service failed

### ISSUE THREAD

**Issue by imranrazakhan** [timescale/timescaledb-kubernetes#315]
I am deploying timescaledb with helm chart "timescaledb-single-0.10.0" on three nodes with image "timescale/timescaledb-ha:pg13.4-ts2.5.0-p0" 

Kubernetes = 1.22.0

But its showing following error

```
2021-11-04 12:52:38,679 ERROR: create_config_service failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 890, in _create_config_service
    if not self._api.create_namespaced_service(self._namespace, body):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 468, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 404, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 373, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 203, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e23f9c8e-0d1f-4f43-a56d-fb53754ce2c2', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Thu, 04 Nov 2021 01:22:10 GMT', 'Content-Length': '129'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}\n'

2021-11-04 12:52:38,725 ERROR: Unexpected error from Kubernetes API
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 483, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 877, in patch_or_create
    return self._patch_or_create(name, annotations, resource_version, patch, retry, ips)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 868, in _patch_or_create
    ret = retry(func, self._namespace, body) if retry else func(self._namespace, body)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 660, in retry
    return retry(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/utils.py", line 334, in __call__
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 468, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 404, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 373, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 203, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '76662621-9cc9-4766-bb50-3c9196284cb1', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Thu, 04 Nov 2021 01:22:10 GMT', 'Content-Length': '129'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}\n'

```

I tried following options but no success

- Change image to  timescale/timescaledb-ha:pg13.4-ts2.4.2-p0
- Give more rights to SA previously it was allowed to create service only

```
  - apiGroups: [""]
    resources: ["services"]
    verbs:
      - create
      - patch
      - get
      - list
```

But still above error is repeating.

**Edit1:**

I deleted whole timescaledb and redeployed and this time i am getting following error

`kubectl -n dev delete $(kubectl -n dev get ep,sa,cm,role,rolebinding,service,sts,pvc,job,secret -l release=yq -o name)`

```
# kubectl -n dev logs -f timescaledb-0 timescaledb
2021-11-04 10:32:26,922 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:27,926 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:28,928 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:29,931 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:30,935 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:31,938 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:32,942 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:33,945 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:34,947 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:35,908 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 704, in _load_cluster
    self._wait_caches(stop_time)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 696, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2021-11-04 10:32:35,909 WARNING: Can not get cluster from dcs
2021-11-04 10:32:35,951 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:36,954 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:37,957 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:38,961 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:39,964 ERROR: ObjectCache.run ApiException()
2021-11-04 10:32:40,968 ERROR: ObjectCache.run ApiException()
```

**Comment by imranrazakhan** [comment]
I deployed in Test Cluster and one of servers time was 30 min back from other, As soon as I synced time across cluster problem get solved.
