### ISSUE TITLE
 can not use patronictl to change the temp_file_limit config

### ISSUE THREAD

**Issue by lrc0** [timescale/timescaledb-kubernetes#87]
I was deploying a timescaledb cluster in my k8s cluster with the image: timescaledev/timescaledb-ha:pg11-ts1.5

I exec:
```
$ patronictl edit-config -p temp_file_limit=10GB
```
but it report a err:
```
Traceback (most recent call last):
  File "/usr/bin/patronictl", line 11, in <module>
    load_entry_point('patroni==1.6.0', 'console_scripts', 'patronictl')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/ctl.py", line 1198, in edit_config
    show_diff(before_editing, after_editing)
  File "/usr/lib/python3/dist-packages/patroni/ctl.py", line 1033, in show_diff
    cdiff.markup_to_pager(cdiff.PatchStream(buf), opts)
  File "/usr/lib/python3/dist-packages/cdiff.py", line 640, in markup_to_pager
    pager_cmd, stdin=subprocess.PIPE, stdout=sys.stdout)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'less': 'less'
```
   
is the docker image not install patronictl correctly？or the command is wrong?

**Comment by feikesteenbergen** [comment]
Thanks for the report, we did not envisage usage of `patronictl` from inside the container, as of the next release changing the configuration can be done by changing your `values.yaml` and doing a `helm upgrade`.

With regards to the error, `patronictl` invokes the pager here:

https://github.com/zalando/patroni/blob/master/patroni/ctl.py#L997

Which seems to be hardcoded by Python Click to be `less`.
We may add `less` to the referenced Docker image however for the next release.

**Comment by feikesteenbergen** [comment]
Any changes made using `patronictl` will be undone on pod reschedule, or on `helm upgrade`, as that will overwrite the dcs with the configuration from `values.yaml`, so I would discourage using `patronictl` for changing the configuration other than during development or troubleshooting.

**Comment by feikesteenbergen** [comment]
This will be part of the next release of the Helm charts, which are expected to be stable within a few days.
